import Head from "next/head"
import { BsFillMoonStarsFill } from "react-icons/bs"
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from "react-icons/ai"
import Image from "next/image"
import img from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Arif Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 flex justify-between">
            <h1 className="text-xl font-burtons">Arif Islam</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl" /></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to bg-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium">MD Arif Islam</h2>
            <h3 className="text-2xl py-2">Full Stack Web Developer & Wordpress Expert.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">Freelancer providing services for programming and design content needs. Join me down below and let's get cracking!</p>
          </div>
          <div className="text-4xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative bg-gradient-to-b from-teal-500 rounded-full h-80 w-80 mx-auto mt-20 overflow-hidden">
            <Image src={img} alt={"img"} layout={"fill"} objectFit={"cover"} />
          </div>
        </section>
        {/* About */}
        <section>
          <div>
            <h3 class="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p class="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Since the beginning of my journey as a freelance designer and developer, I've done remote work for<span class="text-teal-500"> agencies </span>consulted for <span class="text-teal-500">startups </span>and collaborated with talanted people to create digital products for both business and consumer use.</p>
            <p class="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I offer from a wide range of services, including brand design, programming and teaching.</p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10">
              <Image src={design} alt={"design"} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
